# Add services.
volumes:
  mongodb-data-volume:

services:
  mongodb:
    image: mongo:7.0.6-jammy
    container_name: mongodb
    volumes:
      - mongodb-data-volume:/data/db
    ports:
      - 27017:27017
    env_file:
      - .env
    command: --maxConns 1000
    logging:
      options:
        max-size: "10M"
        max-file: "5"

  dash:
    build: app/
    volumes:
      - ./app:/app
    ports:
      - 8050:8050
    env_file:
      - .env
    command: python app.py
    depends_on:
      - mongodb