# Add services.
volumes:
  mongodb-data-volume:

services:
  mongodb:
    image: mongo:7.0.6-jammy
    container_name: mongodb
    volumes:
      - mongodb-data-volume:/data/db
    ports:
      - 27017:27017
    env_file:
      - .env
    command: --maxConns 1000
    logging:
      options:
        max-size: "10M"
        max-file: "5"

  dash:
    build: app/
    volumes:
      - ./app:/app
    ports:
      - 8050:8050
    env_file:
      - .env
    command: python app.py
    depends_on:
      - mongodb

  # Backend for Celery workers.
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

  # Broker for Celery workers.
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11.2-management-alpine
    restart: always
    ports:
      - 15672:15672
      - 5672:5672

  # Celery worker.
  celery_worker:
    container_name: celery_worker
    platform: linux/amd64
    build: app/ ### Should use the same container as fastapi and dash to make requirements easier
    depends_on:
      - redis
      - rabbitmq
    env_file:
      - .env
    environment:
      - REDIS_PASS=devpassword
      - PYTHONBUFFERED=1
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    user: nobody
    volumes:
      - ./app:/app
    command: watchmedo auto-restart --directory=/app --pattern=*.py --recursive --  celery -A app.celery_app  --workdir=/app worker --loglevel=INFO