# Add services.
volumes:
  mongodb-data-volume:

services:
  mongodb:
    image: mongo:7.0.6-jammy
    container_name: neurotk_db
    volumes:
      - mongodb-data-volume:/data/db
    ports:
      - 27017:27017
    env_file: .env
    command: --maxConns 1000
    logging:
      options:
        max-size: "10M"
        max-file: "5"

  dash:
    build: app/
    container_name: neurotk
    platform: linux/amd64
    volumes:
      - ./app:/app
    ports:
      - 8050:8050
    env_file: .env
    command: python app.py
    depends_on:
      - mongodb
      - celery

  # Backend and broker for Celery.
  redis:
    container_name: neurotk_redis
    image: redis:alpine
    restart: always
    env_file: .env
    ports:
      - 6379:6379

  # Celery worker.
  celery:
    container_name: neurotk_worker
    platform: linux/amd64
    build: app/
    depends_on:
      - redis
    env_file: .env
    volumes:
      - ./app:/app
    command: watchmedo auto-restart --directory=/app --pattern=*.py --recursive --  celery -A app.celery_app  --workdir=/app worker --loglevel=INFO